# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a29578c8b18d65ac4217adcecfa500adbdbd3ae193590b68f20a9ab9e067e9e5fabb46dbd25c4e3d64ac815f113739eca4a8e03ee169957643ea123ec80a21

test:
  secret_key_base: 08507e22a7a75bd6e5967395fee65297fbd637ff53a9dde7af370067a6c06d359e0c06e7fdae7957130751d9d8335f670cc7043a69bdc2c36896fceced511e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
